---
openapi: 3.0.1
info:
  title: Api de Notificação
  version: v1
paths:
  "/api/v1/process_tasks":
    post:
      summary: Create a new ProcessTask
      tags:
      - ProcessTasks
      parameters: []
      responses:
        '201':
          description: ProcessTask created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ProcessTask created successfully.
                  process_task:
                    type: object
                    properties:
                      marca:
                        type: string
                        nullable: true
                      modelo:
                        type: string
                        nullable: true
                      valor:
                        type: string
                        nullable: true
                      task_url:
                        type: string
                      task_status:
                        type: integer
                      task_id:
                        type: integer
                      notification_id:
                        type: integer
                      created_at:
                        type: string
                        format: datetime
                      updated_at:
                        type: string
                        format: datetime
                    required:
                    - task_url
                    - task_id
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task_url:
                  type: string
                task_id:
                  type: integer
              required:
              - task_url
              - task_id
