default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_POSTGRES_USER'] %>
  password: <%= ENV['DB_POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_POSTGRES_HOST'] %>
  port: <%= ENV['DB_POSTGRES_PORT'] || 5432 %>

development:
  <<: *default
  database: microservico_webscraping_development

test:
  <<: *default
  database: microservico_webscraping_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
